# INTRODUCTION TO NUMPY

`The goal is to turn data into information, and information into insight.` — Carly Fiorina

### Contents:
- The Basics
- Accessing/Changing specific elements, rows, columns, etc
- Initializing Different Types of Arrays
- Mathematics
- Linear Algebra
- Reorganizing Arrays

##### `Numpy is actually written in C/C++ and we just use python to call those functions.` - Rakshit

In [ ]:
%pip install numpy

In [ ]:
# Basics
import numpy as np
arra = np.array([1., 3, 'a'])
arra

array(['1.0', '3', 'a'], dtype='<U32')

In [ ]:
a = np.array([[1., 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

In [ ]:
a

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [ ]:
a.dtype

dtype('float64')

In [ ]:
a.ndim

2

In [ ]:
a[0:2]

array([[1., 2., 3.],
       [4., 5., 6.]])

In [ ]:
a = np.zeros((5, 5))

In [ ]:
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
b = np.ones((5, 5))
b

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
b[0: 2] = 5
b

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.full((5, 5), 'r')

array([['r', 'r', 'r', 'r', 'r'],
       ['r', 'r', 'r', 'r', 'r'],
       ['r', 'r', 'r', 'r', 'r'],
       ['r', 'r', 'r', 'r', 'r'],
       ['r', 'r', 'r', 'r', 'r']], dtype='<U1')

In [ ]:
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.full_like(a, 4)

array([[4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.]])

In [ ]:
np.

numpy.float64

In [ ]:
np.float32

numpy.float32

In [ ]:
np.dtype

In [ ]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
iden = np.identity(5)

for i in range(5):
    iden[i, i] = 1
iden

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
a = np.random.rand(5, 5)
a

array([[0.45599776, 0.56231541, 0.30405795, 0.82974731, 0.29076478],
       [0.40786575, 0.83373506, 0.47870701, 0.12164333, 0.22731191],
       [0.88472183, 0.65039159, 0.44193424, 0.45140657, 0.38457222],
       [0.15330624, 0.36019886, 0.47766232, 0.31868278, 0.12447512],
       [0.93117152, 0.87991234, 0.84964258, 0.88814576, 0.51984317]])

In [ ]:
a * iden

array([[0.45599776, 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.83373506, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.44193424, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.31868278, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.51984317]])

In [ ]:
mat_1 = np.identity(5) + 1
mat_1

array([[2., 1., 1., 1., 1.],
       [1., 2., 1., 1., 1.],
       [1., 1., 2., 1., 1.],
       [1., 1., 1., 2., 1.],
       [1., 1., 1., 1., 2.]])

In [ ]:
mat_2 = np.array([[1, 2],
                  [3, 4]])

In [ ]:
np.linalg.det(mat_2)

-2.0000000000000004

In [ ]:
np.linalg.inv(mat_2)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [ ]:
np.linalg.det(mat_2)

-2.0000000000000004

In [ ]:


import numpy as np

def matrix_cofactor(matrix):

    try:
        determinant = np.linalg.det(matrix)
        if(determinant!=0):
            cofactor = None
            cofactor = np.linalg.inv(matrix).T * determinant
            # return cofactor matrix of the given matrix
            return cofactor
        else:
            raise Exception("singular matrix")
    except Exception as e:
        print("could not find cofactor matrix due to",e)

print(matrix_cofactor(mat_2))

[[ 4. -3.]
 [-2.  1.]]


In [ ]:
adj = matrix_cofactor(mat_2).T
adj

array([[ 4., -2.],
       [-3.,  1.]])

In [ ]:
mat_3 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])
mat_3.shape

(3, 3)

In [ ]:
mat_3.reshape(1, 3, 3, 1)

array([[[[1],
         [2],
         [3]],

        [[4],
         [5],
         [6]],

        [[7],
         [8],
         [9]]]])

In [ ]:
np.random.rand(10, 10, 3)

array([[[0.74004323, 0.2163028 , 0.02064681],
        [0.6190485 , 0.38188064, 0.816845  ],
        [0.38375612, 0.14514368, 0.38089483],
        [0.38689607, 0.44831376, 0.97097884],
        [0.56536065, 0.17369691, 0.97926312],
        [0.34763996, 0.99932662, 0.89681496],
        [0.98502089, 0.15661932, 0.20565917],
        [0.37044483, 0.49321009, 0.03079719],
        [0.99673079, 0.99347935, 0.72445339],
        [0.1765062 , 0.0238794 , 0.44499104]],

       [[0.34711173, 0.64497347, 0.23075673],
        [0.52076908, 0.94288247, 0.31639676],
        [0.29824894, 0.39319537, 0.75919058],
        [0.62364908, 0.59336051, 0.55503614],
        [0.64321439, 0.49737525, 0.9202161 ],
        [0.93133029, 0.72528398, 0.18736162],
        [0.45337009, 0.53412871, 0.55656803],
        [0.30749641, 0.24511147, 0.73128575],
        [0.78757822, 0.0597151 , 0.02826443],
        [0.98536282, 0.00722919, 0.63203897]],

       [[0.99363082, 0.99109706, 0.75440278],
        [0.90632861, 0.0025629

## INTEGRATION

In [ ]:
import numpy as np

In [ ]:
x = np.linspace(1, 15, num=10000)
x

array([ 1.        ,  1.00140014,  1.00280028, ..., 14.99719972,
       14.99859986, 15.        ])

In [ ]:
x = np.linspace(0.0000000000001, 10000, num=1000)
y = np.log(1+x**2)/x**2
np.trapz(y, x)

0.9434455584030152

In [ ]:
import numpy as np

def distFunc(x,y):
    f = np.exp(-x+y)
    return f

# Values in x to evaluate the integral.
x = np.linspace(.1, 10, 100)
y = np.linspace(.1, 10, 100)
X, Y = np.meshgrid(x, y)

list1=distFunc(X, Y)
int_exp2d = np.trapz(np.trapz(list1, y, axis=0), x, axis=0)
int_exp2d

19961.5927394128

In [ ]:
scipy

In [ ]:
np.min

<function numpy.amin(a, axis=None, out=None, keepdims=<no value>, initial=<no value>, where=<no value>)>

In [ ]:
np.pi

3.141592653589793

In [ ]:
import math

math.pi ** 3

31.006276680299816